In [1]:
import pandas as pd

In [4]:
stats_1_df = pd.read_excel(r'C:\Users\Sean\Documents\GitHub\tennis_betting\Data\OnCourt Data\stat_atp_1.xlsx')
stats_2_df = pd.read_excel(r'C:\Users\Sean\Documents\GitHub\tennis_betting\Data\OnCourt Data\stat_atp_2.xlsx')
stats_3_df = pd.read_excel(r'C:\Users\Sean\Documents\GitHub\tennis_betting\Data\OnCourt Data\stat_atp_3.xlsx')
stats_4_df = pd.read_excel(r'C:\Users\Sean\Documents\GitHub\tennis_betting\Data\OnCourt Data\stat_atp_4.xlsx')

In [6]:
dfs = [stats_1_df,stats_2_df,stats_3_df,stats_4_df]
stats_df = pd.concat(dfs)

In [7]:
len(stats_df)

203521

In [8]:
stats_df.head()

,ID1,ID2,ID_T,ID_R,FS_1,FSOF_1,ACES_1,DF_1,UE_1,W1S_1,...,NAOF_2,TPW_2,FAST_2,A1S_2,A2S_2,RPW_1,RPWOF_1,RPW_2,RPWOF_2,MT
0,401,921,2205,1,52.0,91.0,1.0,2.0,25.0,37.0,...,32.0,83.0,NaN,NaN,NaN,31.0,78.0,36.0,91.0,NaN
1,65,706,2205,1,37.0,71.0,3.0,6.0,28.0,27.0,...,10.0,62.0,NaN,NaN,NaN,31.0,67.0,26.0,71.0,NaN
2,77,406,2205,1,32.0,50.0,4.0,0.0,7.0,26.0,...,26.0,46.0,NaN,NaN,NaN,23.0,58.0,11.0,50.0,NaN
3,840,666,2205,2,50.0,75.0,4.0,2.0,31.0,29.0,...,29.0,80.0,NaN,NaN,NaN,38.0,86.0,32.0,75.0,NaN
4,831,880,2205,2,49.0,79.0,11.0,5.0,43.0,37.0,...,11.0,73.0,NaN,NaN,NaN,34.0,81.0,26.0,79.0,NaN

In [9]:
tours_df = pd.read_excel(r'C:\Users\Sean\Documents\GitHub\tennis_betting\Data\OnCourt Data\tours_atp.xlsx')

In [10]:
tours_df.head()

,ID_T,NAME_T,ID_C_T,DATE_T,RANK_T,LINK_T,COUNTRY_T,PRIZE_T,RATING_T,URL_T,...,SITE_T,RACE_T,ENTRY_T,SINGLES_T,DOUBLES_T,TIER_T,RESERVE_INT_T,RESERVE_CHAR_T,LIVE_T,RESULT_T
0,2114,Adelaide,Hard,1990-01-01,2,NaN,AUS,$125K,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2115,Wellington,Hard,1990-01-01,2,NaN,NZL,$125K,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2116,Auckland,Hard,1990-01-08,2,NaN,NZL,$125K,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2117,Sydney,Hard,1990-01-08,2,NaN,AUS,$150K,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2118,Australian Open,Hard,1990-01-15,4,NaN,AUS,$1462K,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
tour_id_order = tours_df['ID_T'].values
tour_id_order

array([ 2114,  2115,  2116, ..., 15669, 15670, 15671], dtype=int64)

In [16]:
stats_df.ID_T = stats_df.ID_T.astype("category")
stats_df.ID_T.cat.set_categories(tour_id_order, inplace=True)


stats_df.sort_values(["ID_T"])

,ID1,ID2,ID_T,ID_R,FS_1,FSOF_1,ACES_1,DF_1,UE_1,W1S_1,...,NAOF_2,TPW_2,FAST_2,A1S_2,A2S_2,RPW_1,RPWOF_1,RPW_2,RPWOF_2,MT
201,71,87,1111,4,51.0,82.0,14.0,3.0,41.0,38.0,...,11.0,69.0,NaN,NaN,NaN,35.0,79.0,25.0,82.0,NaN
252,472,75,1111,5,71.0,167.0,0.0,12.0,112.0,52.0,...,22.0,167.0,NaN,NaN,NaN,67.0,162.0,72.0,167.0,NaN
251,116,301,1111,5,54.0,86.0,5.0,4.0,32.0,45.0,...,30.0,81.0,NaN,NaN,NaN,42.0,102.0,21.0,86.0,NaN
250,444,487,1111,5,77.0,133.0,22.0,9.0,83.0,63.0,...,19.0,129.0,NaN,NaN,NaN,51.0,134.0,46.0,133.0,NaN
249,20,673,1111,5,58.0,123.0,6.0,5.0,83.0,44.0,...,28.0,117.0,181.0,157.0,130.0,63.0,129.0,51.0,123.0,NaN
248,53,90,1111,5,41.0,71.0,14.0,5.0,54.0,38.0,...,16.0,76.0,173.0,146.0,129.0,39.0,100.0,15.0,71.0,NaN
247,66,631,1111,5,81.0,119.0,6.0,4.0,83.0,53.0,...,10.0,122.0,185.0,168.0,133.0,52.0,126.0,48.0,119.0,NaN
246,30,37,1111,5,67.0,104.0,1.0,6.0,47.0,48.0,...,72.0,96.0,205.0,181.0,136.0,60.0,121.0,35.0,104.0,NaN
245,3,670,1111,5,83.0,145.0,8.0,4.0,77.0,53.0,...,51.0,145.0,202.0,189.0,150.0,62.0,144.0,63.0,145.0,NaN
244,47,497,1111,5,81.0,127.0,2.0,11.0,74.0,52.0,...,32.0,108.0,191.0,172.0,131.0,54.0,109.0,53.0,127.0,NaN
243,611,6,1111,5,93.0,147.0,8.0,2.0,108.0,56.0,...,40.0,149.0,194.0,164.0,134.0,74.0,168.0,55.0,147.0,NaN
242,24,16,1111,5,48.0,97.0,15.0,7.0,63.0,42.0,...,23.0,88.0,213.0,196.0,151.0,42.0,100.0,30.0,97.0,NaN
241,681,110,1111,4,84.0,121.0,3.0,7.0,62.0,58.0,...,67.0,112.0,NaN,NaN,NaN,53.0,126.0,39.0,121.0,NaN
240,361,58,1111,4,52.0,106.0,12.0,4.0,47.0,43.0,...,34.0,100.0,NaN,NaN,NaN,61.0,130.0,31.0,106.0,NaN
239,17,76,1111,4,64.0,107.0,10.0,3.0,55.0,47.0,...,25.0,100.0,NaN,NaN,NaN,42.0,107.0,35.0,107.0,NaN
238,84,736,1111,4,77.0,109.0,5.0,4.0,61.0,50.0,...,73.0,124.0,NaN,NaN,NaN,53.0,128.0,49.0,109.0,NaN
237,515,15,1111,4,44.0,63.0,4.0,2.0,29.0,33.0,...,38.0,56.0,NaN,NaN,NaN,41.0,79.0,18.0,63.0,NaN
236,31,83,1111,4,49.0,91.0,7.0,7.0,50.0,40.0,...,21.0,97.0,NaN,NaN,NaN,61.0,129.0,29.0,91.0,NaN
235,41,692,1111,4,81.0,156.0,8.0,10.0,53.0,60.0,...,78.0,148.0,NaN,NaN,NaN,52.0,133.0,67.0,156.0,NaN
234,99,553,1111,4,72.0,115.0,7.0,3.0,49.0,56.0,...,29.0,109.0,NaN,NaN,NaN,52.0,128.0,33.0,115.0,NaN
233,86,79,1111,4,98.0,129.0,2.0,1.0,51.0,63.0,...,33.0,116.0,NaN,NaN,NaN,52.0,115.0,53.0,129.0,NaN
232,35,43,1111,4,41.0,80.0,2.0,1.0,16.0,30.0,...,38.0,65.0,NaN,NaN,NaN,38.0,81.0,22.0,80.0,NaN
253,74,18,1111,5,46.0,86.0,7.0,3.0,56.0,27.0,...,21.0,81.0,199.0,163.0,133.0,57.0,99.0,39.0,86.0,NaN
254,78,92,1111,5,92.0,177.0,7.0,5.0,126.0,62.0,...,28.0,175.0,196.0,157.0,136.0,75.0,173.0,77.0,177.0,NaN
255,69,57,1111,5,40.0,70.0,9.0,1.0,30.0,34.0,...,7.0,56.0,NaN,NaN,NaN,28.0,68.0,16.0,70.0,NaN
256,492,424,1111,5,61.0,104.0,7.0,5.0,49.0,44.0,...,31.0,93.0,NaN,NaN,NaN,60.0,117.0,36.0,104.0,NaN
278,47,20,1111,6,76.0,130.0,3.0,3.0,73.0,43.0,...,30.0,121.0,199.0,167.0,128.0,44.0,112.0,53.0,130.0,NaN
277,30,472,1111,6,37.0,60.0,1.0,0.0,20.0,27.0,...,37.0,56.0,204.0,186.0,145.0,45.0,87.0,14.0,60.0,NaN
276,24,492,1111,6,69.0,148.0,9.0,14.0,91.0,51.0,...,35.0,137.0,188.0,171.0,143.0,59.0,131.0,65.0,148.0,NaN
275,3,78,1111,6,76.0,108.0,3.0,1.0,43.0,51.0,...,16.0,98.0,196.0,181.0,133.0,36.0,99.0,35.0,108.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23155,2123,26845,15606,1,27.0,47.0,1.0,2.0,13.0,22.0,...,18.0,40.0,NaN,NaN,NaN,21.0,51.0,10.0,47.0,01:13:00
23154,18485,33860,15606,1,34.0,56.0,5.0,1.0,24.0,29.0,...,13.0,58.0,NaN,NaN,NaN,29.0,75.0,12.0,56.0,01:20:00
23153,20465,20542,15606,1,45.0,77.0,4.0,1.0,28.0,29.0,...,7.0,69.0,NaN,NaN,NaN,29.0,70.0,28.0,77.0,01:32:00
23152,12587,6431,15606,1,37.0,57.0,5.0,4.0,15.0,28.0,...,30.0,59.0,NaN,NaN,NaN,33.0,75.0,17.0,57.0,01:15:00
23151,9833,28263,15606,1,30.0,44.0,5.0,0.0,15.0,23.0,...,11.0,33.0,NaN,NaN,NaN,29.0,49.0,13.0,44.0,00:57:00
23150,7345,22429,15606,1,44.0,62.0,3.0,1.0,22.0,34.0,...,18.0,57.0,NaN,NaN,NaN,32.0,71.0,18.0,62.0,01:14:00
23149,27358,1747,15606,1,43.0,66.0,1.0,6.0,23.0,31.0,...,16.0,56.0,NaN,NaN,NaN,31.0,61.0,26.0,66.0,01:28:00
23148,26381,36263,15606,1,48.0,68.0,11.0,6.0,31.0,40.0,...,8.0,68.0,194.0,NaN,NaN,34.0,80.0,22.0,68.0,01:28:00
23147,40434,12871,15606,1,35.0,54.0,10.0,3.0,21.0,30.0,...,14.0,51.0,NaN,NaN,NaN,32.0,71.0,12.0,54.0,01:18:00
23146,8313,3833,15606,1,56.0,85.0,9.0,5.0,31.0,39.0,...,13.0,82.0,NaN,NaN,NaN,32.0,83.0,31.0,85.0,02:00:00
23145,41964,1113,15606,1,38.0,69.0,4.0,2.0,25.0,26.0,...,12.0,66.0,NaN,NaN,NaN,22.0,68.0,20.0,69.0,01:15:00
23144,7393,11981,15606,1,70.0,99.0,2.0,2.0,38.0,44.0,...,3.0,103.0,NaN,NaN,NaN,40.0,101.0,42.0,99.0,02:14:00
23143,31392,28992,15606,1,37.0,65.0,7.0,1.0,15.0,28.0,...,27.0,48.0,NaN,NaN,NaN,28.0,54.0,22.0,65.0,01:30:00
23439,34337,14609,15606,3,31.0,48.0,3.0,1.0,9.0,25.0,...,8.0,33.0,NaN,NaN,NaN,19.0,40.0,12.0,48.0,01:01:00
23438,28898,14536,15606,3,42.0,65.0,4.0,1.0,10.0,33.0,...,14.0,45.0,NaN,NaN,NaN,14.0,39.0,21.0,65.0,00:58:00
23437,7295,19910,15606,3,54.0,82.0,6.0,0.0,46.0,38.0,...,19.0,79.0,181.0,NaN,NaN,36.0,90.0,26.0,82.0,01:52:00
23436,17123,12653,15606,3,61.0,97.0,6.0,1.0,22.0,42.0,...,27.0,94.0,NaN,NaN,NaN,34.0,96.0,35.0,97.0,02:11:00
23435,10415,11521,15606,3,27.0,40.0,14.0,0.0,10.0,24.0,...,4.0,32.0,188.0,NaN,NaN,22.0,48.0,8.0,40.0,01:06:00
23434,36449,4003,15606,3,50.0,69.0,9.0,3.0,14.0,37.0,...,35.0,57.0,NaN,NaN,NaN,31.0,69.0,17.0,69.0,01:14:00
23433,22432,6820,15606,3,43.0,67.0,18.0,2.0,17.0,33.0,...,14.0,62.0,192.0,NaN,NaN,19.0,62.0,19.0,67.0,01:30:00
23432,48442,20819,15606,3,48.0,92.0,11.0,5.0,29.0,35.0,...,15.0,91.0,NaN,NaN,NaN,24.0,88.0,28.0,92.0,01:40:00
23431,12097,23298,15606,3,24.0,56.0,6.0,2.0,31.0,17.0,...,10.0,57.0,NaN,NaN,NaN,32.0,65.0,24.0,56.0,01:34:00
23430,13445,6831,15606,3,61.0,91.0,3.0,2.0,36.0,40.0,...,11.0,84.0,NaN,NaN,NaN,41.0,88.0,39.0,91.0,02:14:00
23429,12430,32729,15606,3,67.0,98.0,1.0,0.0,31.0,46.0,...,12.0,97.0,NaN,NaN,NaN,38.0,107.0,32.0,98.0,02:10:00
23428,12614,18612,15606,3,40.0,68.0,7.0,4.0,30.0,35.0,...,11.0,66.0,NaN,NaN,NaN,36.0,81.0,17.0,68.0,01:35:00
23427,9305,2123,15606,3,30.0,46.0,3.0,1.0,12.0,24.0,...,27.0,48.0,NaN,NaN,NaN,31.0,68.0,11.0,46.0,01:27:00
23426,18485,12587,15606,3,69.0,111.0,18.0,1.0,27.0,58.0,...,24.0,104.0,206.0,NaN,NaN,41.0,120.0,29.0,111.0,02:20:00
23425,26381,27358,15606,3,34.0,47.0,12.0,1.0,17.0,29.0,...,11.0,43.0,NaN,NaN,NaN,19.0,58.0,9.0,47.0,01:02:00
23159,12614,33648,15606,1,23.0,47.0,5.0,1.0,18.0,22.0,...,7.0,42.0,198.0,NaN,NaN,24.0,56.0,10.0,47.0,01:10:00
23348,14609,20654,15606,2,44.0,52.0,4.0,0.0,12.0,32.0,...,4.0,40.0,NaN,NaN,NaN,19.0,49.0,12.0,52.0,00:57:00