In [8]:
import sklearn
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [9]:
results_df = pd.read_excel('Data/2004.xls')

for i in range (2005,2012):
    results_df.append(pd.read_excel('Data/' + str(i) + '.xls'))
    

for i in range (2013,2018):
    results_df.append(pd.read_excel('Data/' + str(i) + '.xlsx'))

results_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,B365W,B365L,CBW,CBL,EXW,EXL,IWW,IWL,PSW,PSL
0,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Spadea V.,...,NaN,NaN,1.40,2.85,1.48,2.53,1.45,2.20,1.465,2.900
1,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Dent T.,...,1.16,4.50,1.22,4.10,1.20,4.45,1.20,3.30,1.241,4.550
2,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Martin A.,...,2.00,1.72,2.15,1.67,NaN,NaN,2.00,1.55,2.170,1.752
3,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Beck K.,...,1.83,1.83,1.70,2.10,NaN,NaN,NaN,NaN,1.730,2.210
4,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Nieminen J.,...,1.40,2.75,1.40,2.85,1.50,2.45,1.35,2.50,1.459,2.930

In [10]:
list(results_df.columns)

['ATP',
 'Location',
 'Tournament',
 'Date',
 'Series',
 'Court',
 'Surface',
 'Round',
 'Best of',
 'Winner',
 'Loser',
 'WRank',
 'LRank',
 'W1',
 'L1',
 'W2',
 'L2',
 'W3',
 'L3',
 'W4',
 'L4',
 'W5',
 'L5',
 'Wsets',
 'Lsets',
 'Comment',
 'B365W',
 'B365L',
 'CBW',
 'CBL',
 'EXW',
 'EXL',
 'IWW',
 'IWL',
 'PSW',
 'PSL']

In [11]:
results_df['W_Best'] = results_df[['B365W','PSW']].max(axis=1)
results_df['L_Best'] = results_df[['B365L','PSL']].max(axis=1)

results_df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,CBW,CBL,EXW,EXL,IWW,IWL,PSW,PSL,W_Best,L_Best
0,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Spadea V.,...,1.40,2.85,1.48,2.53,1.45,2.20,1.465,2.900,1.465,2.900
1,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Dent T.,...,1.22,4.10,1.20,4.45,1.20,3.30,1.241,4.550,1.241,4.550
2,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Martin A.,...,2.15,1.67,NaN,NaN,2.00,1.55,2.170,1.752,2.170,1.752
3,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Beck K.,...,1.70,2.10,NaN,NaN,NaN,NaN,1.730,2.210,1.830,2.210
4,1,Adelaide,AAPT Championships,2004-01-05,International,Outdoor,Hard,1st Round,3,Nieminen J.,...,1.40,2.85,1.50,2.45,1.35,2.50,1.459,2.930,1.459,2.930

In [4]:
num_matches = len(results_df)
num_matches

2877